version: '3.8'
services:
  frontend:
    build: ./front
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:12345@db:5432/matchadb

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
